theme: jekyll-theme-minimal
url: https://chan811.github.io/
<img src="{{site.url}}/images/imageChanly.jpg" style="display: block; margin: auto;" />
title: Chanly Ly
description: I am a computer engineering student at UCSD
