theme: jekyll-theme-minimal
url: https://chan811.github.io/
image: ![Image](https://chan811.github.io/images/imageChanly.png)
title: Chanly Ly
description: I am a computer engineering student at UCSD
